title: "Glasgow Memory (GLAM) Lab"
description: "Glasgow Memory Lab (GLAM Lab, PI: Maria Wimber), based in School of Psychology & Neuroscience, University of Glasgow"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

markdown: kramdown

# Minimal navigation (will expand later)
nav:
  - title: "Home"
    url: /
  - title: "People"
    url: /people/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/
  - title: "News"
    url: /news/


# Enable the header navigation bar
header:
  nav: true

